export const biathlonData = [
    {
        id: 1,
        rank: 1,
        name: "LAEGREID Sturla Holm",
        shooting: "49",
        speed: "20",
      },
      {
        id: 2,
        rank: 2,
        name: "BOE Johannes Thingnes",
        shooting: "48",
        speed: "21",
      },
      {
        id: 3,
        rank: 3,
        name: "LESSER Erik",
        shooting: "47,5",
        speed: "21,5",
      },
      {
        id: 4,
        rank: 4,
        name: "FILLON MAILLET Quentin",
        shooting: "45",
        speed: "22",
      },
      {
        id: 5,
        rank: 5,
        name: "MORAVEC Ondrej",
        shooting: "43,08",
        speed: "24",
      },
      {
        id: 6,
        rank: 6,
        name: "SAMUELSSON Sebastian",
        shooting: "42,72",
        speed: "21",
      },
      {
        id: 7,
        rank: 7,
        name: "FAK Jakov",
        shooting: "41,99",
        speed: "25,33",
      },
      {
        id: 8,
        rank: 8,
        name: "JACQUELIN Emilien",
        shooting: "41,6",
        speed: "26",
      },
      {
        id: 9,
        rank: 9,
        name: "GUIGONNAT Antonin",
        shooting: "41%",
        speed: "27",
      },
      {
        id: 10,
        rank: 10,
        name: "LOGINOV Alexander",
        shooting: "40,8",
        speed: "27,01",
      },
];